### ISSUE TITLE
Migrate from travis-ci.org

### ISSUE THREAD

**Issue by mwild1** [xsf/infrastructure#13]
travis-ci.org is shutting down "at the end of May". Meanwhile travis-ci.com remains open (their new platform), though with a more restrictive free tier.

I've migrated from travis-ci.org ->travis-ci.com. The dashboard is a bit weird and doesn't show credits or plan info, so I'm just giving it some time. If necessary I shall contact them to request sponsored OSS credits.

If for any reason this migration falls through, we'll migrate to Github Actions.

**Comment by cal0pteryx** [comment]
@mwild1 ping, this can be closed :)
