### ISSUE TITLE
Provide filtered XMPP provider lists on https://xmpp.net

### ISSUE THREAD

**Issue by melvo** [xsf/infrastructure#14]
@mwild1 proposed that a subdomain of https://xmpp.net could provide the filtered lists of category A, B and C of the [**XMPP Providers** project](https://invent.kde.org/melvo/xmpp-providers).

## Steps

1. `git clone https://invent.kde.org/melvo/xmpp-providers.git && cd xmpp-providers` only once
2. `git pull && ./filter.py -A && ./filter.py -B && ./filter.py -C` once a day or even more often

## Software Requirements

Python >= 3.7 is required for running `./filter.py`.

## Additional Thoughts

We could link from https://invent.kde.org/melvo/xmpp-providers to the three created JSON files on https://providers.xmpp.net or a similar subdomain.
It would be great if we could provide those lists as a first easy goal. In the future, we could create a welcome page with links to all lists or even a nice formatted table on https://providers.xmpp.net.

**Comment by melvo** [comment]
@Echolon This is the issue for providing the filtered lists by a web server.

**Comment by Echolon** [comment]
Great @melvo

**Comment by mwild1** [comment]
Thanks for filing this! If someone can put together a Dockerfile, it should be pretty easy to get deployed. Otherwise I'll try to do it, but whether I have time this week depends on how the jabber.org migration goes.

**Comment by Echolon** [comment]
@mwild1 great - thanks for your support. lets see what we can do here!

**Comment by mwild1** [comment]
I've made a Dockerfile for this, but I'm uneasy about the automatic git pull from a non-XSF code repository. If the repository were ever compromised, it would allow executing arbitrary code on our server (within a container, but containers are not sufficient for isolation of untrusted code).

Some options that *would* be okay:

- Automatic update of non-code files only (e.g. auto-update for providers.json, but not filter.py)
- Pulling pre-built JSON files from somewhere else
- Moving the repo to github.com/xsf so that XSF iteam members can review and approve changes to the code before they are deployed.

**Comment by melvo** [comment]
@mwild1 Thanks!

The latest provider lists are now  automatically created and must only be fetched:
[providers-A.json](https://invent.kde.org/melvo/xmpp-providers/-/jobs/artifacts/master/raw/providers-A.json?job=filtered-provider-lists)
[providers-B.json](https://invent.kde.org/melvo/xmpp-providers/-/jobs/artifacts/master/raw/providers-B.json?job=filtered-provider-lists)
[providers-C.json](https://invent.kde.org/melvo/xmpp-providers/-/jobs/artifacts/master/raw/providers-C.json?job=filtered-provider-lists)

I propose to do that once a day if possible.

**Comment by Echolon** [comment]
Category A via data.xmpp.net

https://data.xmpp.net/providers/v1/providers-A.json

**Comment by mwild1** [comment]
They are (now) and yes, I have. Thanks for your patience :)

**Comment by Echolon** [comment]
❤❤❤

**Comment by melvo** [comment]
@mwild1 Thanks! I created two new issues (#18 and #19) for the next steps :)
