### ISSUE TITLE
XMPP Providers badges and results on https://data.xmpp.net

### ISSUE THREAD

**Issue by melvo** [xsf/infrastructure#19]
There are already [badges for XMPP providers](https://invent.kde.org/melvo/xmpp-providers#badges). Those badges could be hosted on https://data.xmpp.net. In addition, a page for each provider result could explain it and describe how it can be improved.

At the moment, there is only a JSON file listing the issues that must be resolved in order to be in a specific [category](https://invent.kde.org/melvo/xmpp-providers#categories). After clicking on the badge a provider embedded in its website, the JSON file is opened (see https://hookipa.net in the row **hookipa.net** for an example). The current state is only meant as a temporary solution since users and admins do not know what the JSON content means.

The proposed result page could outline the project's goals including a link to the [upcoming introduction page](xsf/xmpp.org#1083), use the JSON file in order to represent it as text or even graphically and provide help for the provider's admins.

**Comment by mwild1** [comment]
Who is going to do this work? I'm not sure it's an XSF iteam issue. We're happy to host projects on xmpp.net, but what you're describing requires some amount of design and development effort. I don't think we have the resources to develop something like this (we're barely managing the observatory already).

**Comment by melvo** [comment]
There are two tasks:
1. Fetching all badges from our GitLab instance and providing them on xmpp.net: Currently, there are only links for each XMPP provider (e.g., https://invent.kde.org/melvo/xmpp-providers/-/jobs/artifacts/master/raw/badges/example.org.svg?job=badges) but we could create a tar file containing all of them. @mwild1 Could you fetch and provide the badges on xmpp.net?
1. Creating the corresponding result pages: We could generate HTML or Markdown pages for the results. @mwild1 Could you fetch and provide them on xmpp.net?

**Comment by wurstsalat3000** [comment]
@melvo I'm interested! Would that be a page, say providers.xmpp.net, that lists all providers from xmpp-providers including badges? Plus details page (or something like that) for each one?

**Comment by melvo** [comment]
@wurstsalat3000 Cool :) Thanks for your interest!

The original idea was to have a [page with all providers on xmpp.org](https://github.com/xsf/xmpp.org/issues/1083). But such a table should probably not include the rating ([category A, B or C](https://invent.kde.org/melvo/xmpp-providers#categories)) because of the XSF's autonomy. Thus, we maybe should create such a page on xmpp.net and only create an introduction page on xmpp.org containing a link to the table on xmpp.net. That table could list all providers with their [criteria](https://invent.kde.org/melvo/xmpp-providers#criteria) and categories.

The badges show only the category and are only intended to be embedded in the providers' websites. Therefore, the table listing all providers should not show the badges. It should have a column for the category instead. But the colors of the badges could be used for the rows to indicate if a provider is in a specific category.

After clicking on a row / provider, a details page for that provider could then be opened. It should contain all [properties](https://invent.kde.org/melvo/xmpp-providers#properties), explain why the provider is in a specific category and how to improve the current rating. That details page could also be used as the page that is opened when clicking on a badge (called *result page* in this issue's description). The generation of the explanation should use the JSON file created for each provider (e.g., https://invent.kde.org/melvo/xmpp-providers/-/jobs/artifacts/master/raw/results/draugr.de.json?job=filtered-provider-lists).

I think it would be best to start creating the page on xmpp.net with the table listing all providers with their categories and subsequently add the remaining functionalities. As soon as a minimal table is there, we can create the introduction page on xmpp.org and link to the page on xmpp.net.

**Comment by melvo** [comment]
Thanks @wurstsalat3000 for your great work on the new website! We will manage all related issues in its [new repository](https://github.com/xsf/xmpp-providers-website).
