### ISSUE TITLE
Move Prosody into Docker

### ISSUE THREAD

**Issue by Zash** [xsf/infrastructure#2]
To gain independence from the host OS and consistency with other services that are running in Docker.

**Comment by Zash** [comment]
Since the host is now Debian 10 "Buster" instead of oldoldoldstable, this is not as acute anymore. Available versions of various software are more easily available.

**Comment by mwild1** [comment]
I think this is done now?

**Comment by Zash** [comment]
Not done. Hasn't been seen as a priority since the host is running a recent OS that can just upgrade to a recent version of Prosody.

Also with the current troubles with the [Prosody Docker image](https://github.com/prosody/prosody-docker/issues/72)

**Comment by mwild1** [comment]
Makes sense, WONTFIX then
